### ISSUE TITLE
请问怎样训练

### ISSUE THREAD

**Issue by 17702513221** [woshichaoren000/smokeRecognize#1]
能提供下几张训练的数据吗，我按相同格式训练一下模型，训练脚本也希望可以告诉我怎样用，谢谢

**Comment by chasezcz** [comment]
链接: https://pan.baidu.com/s/1WNanhuZWp7_zOOG5uM2FMA 提取码: sqbg 
这是我之前参考的学长资料和数据集，2000的数据其实是不够的，需要你自己去爬一点，2000的话训练出来模型的准确率大约在94左右，图像大小是32x32的（特征向量的维度和图像大小并不完全挂钩，只需要后期调整一下就行）
训练脚本没单独写，集成在一起了，在svm.py里train()里，参数调整啥的自己看情况修改一下。
这个其实还有很多地方没完成，准确度不够，还需要调整，一起改吧哈哈
